services:
  server1:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    container_name: server1
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODES=["server2:5001", "server3:5002"]
    networks:
      - blockchain_net

  server2:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    container_name: server2
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODES=["server1:5000", "server3:5002"]
    networks:
      - blockchain_net

  server3:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    container_name: server3
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - NODES=["server1:5000", "server2:5001"]
    networks:
      - blockchain_net

networks:
  blockchain_net:
    driver: bridge
